version: '3.8'

services:
  mysql:
    image: mysql:5.7 # or whichever version you prefer
    environment:
      MYSQL_DATABASE: 'Tracker'
      MYSQL_USER: 'root' # It's common to just use the root user for simplicity
      MYSQL_PASSWORD: 'asdf1234' # Same as in your Node.js app config
      MYSQL_ROOT_PASSWORD: 'asdf1234'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: 
      --init-file /docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql # This will point to the MySQL service in Docker
      - DB_PORT=3306 # Internal MySQL port
      - DB_USER=root
      - DB_PASSWORD=asdf1234
      - DB_NAME=Tracker
    depends_on:
      - mysql
    command: node index.js

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: npm start

volumes:
  mysql-data:
